<?php


namespace backend\controllers;

use backend\models\RequestConfig;
use backend\components\CurlInterface;
use backend\models\search\UserProductBlacklistSearch;
use backend\models\TLmfApiProductInfoContact;
use Yii;

class UserProductBlacklistController extends BaseController
{

    public function init()
    {
        parent::behaviors(); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        $searchModel = new UserProductBlacklistSearch();
        $postArr = isset(Yii::$app->request->queryParams['UserProductBlacklistSearch']) ? Yii::$app->request->queryParams['UserProductBlacklistSearch'] : [];
//        $this->log(json_encode(Yii::$app->request->queryParams));
        $arr = [];
        if (isset($postArr['id'])) {
            $data = ['phoneNo' => $postArr['id']];
            $curl = new  CurlInterface(json_encode($data), 6);
            $model = RequestConfig::findOne(['request_fun' => 'black_product']);
            $result = $curl->execute($model->request_url, 'POST');
            $arr = $result['data']['productList'];
            $searchModel->id = $postArr['id'];
        }
        $dataProvider = $searchModel->search($arr);
//        $res = $tp->getAppName($arr);
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
}